---
data:
    name: cifar10
    binary: true
    flatten: true
    replace_index: 1
model:
    architecture: logistic
    diffinit: true
    task_type: binary
    input_size: 50
    output_size: 1
    hidden_size:
training:
    seed: 1
    n_epochs: 25
    batch_size: 32
    optimization_algorithm:
        name: SGD
        learning_rate: 0.5
logging:
    cadence: 50
    save_weights: true
    save_gradients: true
    sample_minibatch_gradients: false
    n_gradients: 0
...
