---
data:
    name: cifar10
    binary: true
    flatten: true
model:
    architecture: logistic
    task_type: binary
    input_size: 50
    output_size: 1
    hidden_size:
training:
    n_epochs: 5
    batch_size: 32
    optimization_algorithm:
        name: SGD
        learning_rate: 0.5
logging:
    cadence: 1
    save_weights: true
    save_gradients: true
    sample_minibatch_gradients: true
    n_gradients: 50
...
