---
data:
    name: cifar100
    binary: false
model:
    architecture: cnn_cifar
    task_type: classification
    input_size: !!python/tuple [32, 32, 3]
    output_size: 100
    hidden_size: 16
training:
    n_epochs: 2
    batch_size: 64
    optimization_algorithm:
        name: adam
        learning_rate: 0.001
logging:
    cadence: 5000
    save_weights: false
    save_gradients: false
    sample_minibatch_gradients: false
    n_gradients: 0
...
