---
data:
    name: mnist
    binary: false
    flatten: false
model:
    architecture: cnn
    task_type: classification
    input_size: (32, 32, 3)
    output_size: 10
    hidden_size: 16
training:
    n_epochs: 2
    batch_size: 32
    optimization_algorithm:
        name: SGD
        learning_rate: 0.1
logging:
    cadence: 50
    save_weights: true
    save_gradients: true
    sample_minibatch_gradients: false
    n_gradients: 0
...
