---
data:
    name: cifar10_pretrain
    binary: true
model:
    architecture: mlp
    task_type: binary
    input_size: 64
    output_size: 1
    hidden_size: 10
training:
    n_epochs: 25
    batch_size: 32
    optimization_algorithm:
        name: SGD
        learning_rate: 0.25
logging:
    cadence: 50
    save_weights: true
    save_gradients: false
    sample_minibatch_gradients: false
    n_gradients: 0
...
