---
data:
    name: forest
    binary: true
model:
    architecture: logistic
    task_type: binary
    input_size: 49
    output_size: 1
    hidden_size: 8
training:
    n_epochs: 4
    batch_size: 50
    optimization_algorithm:
        name: SGD
        learning_rate: 1.0
logging:
    cadence: 100
    save_weights: true
    save_gradients: true
    sample_minibatch_gradients: false
    n_gradients: 0
...
