---
data:
    name: housing
    binary: false
model:
    architecture: linear
    task_type: regression
    input_size: 13
    output_size: 1
    hidden_size: 8
training:
    n_epochs: 50
    batch_size: 28
    optimization_algorithm:
        name: SGD
        learning_rate: 0.01
logging:
    cadence: 50
    save_weights: true
    save_gradients: true
    sample_minibatch_gradients: false
    n_gradients: 0
...
