---
data:
    name: mnist
    binary: false
    flatten: true
    preprocessing: PCA 
model:
    architecture: mlp
    task_type: classification
    input_size: 50
    output_size: 10
    hidden_size: 5
training:
    n_epochs: 3
    batch_size: 32
    optimization_algorithm:
        name: SGD
        learning_rate: 0.1
logging:
    cadence: 50
    save_weights: true
    save_gradients: true
    sample_minibatch_gradients: false
    n_gradients: 0
...
