---
data:
    name: mvn
    binary: false
model:
    architecture: linear
    task_type: regression
    input_size: 25
    output_size: 1
    hidden_size: 32
training:
    n_epochs: 2
    batch_size: 32
    optimization_algorithm:
        name: SGD
        learning_rate: 0.01
logging:
    cadence: 5
    save_weights: true
    save_gradients: true
    sample_minibatch_gradients: false
    n_gradients: 0
...
