---
data:
    name: protein
    binary: true
    replace_index: 1
model:
    architecture: logistic
    diffinit: true
    task_type: binary
    input_size: 74
    output_size: 1
    hidden_size: 8
training:
    seed: 1
    n_epochs: 3
    batch_size: 50
    optimization_algorithm:
        name: SGD
        learning_rate: 0.01
logging:
    cadence: 100
    save_weights: true
    save_gradients: true
    sample_minibatch_gradients: false
    n_gradients: 0
...
